language: node_js
node_js:
- '6'
before_install:
- echo "registry = https://realglobe.artifactoryonline.com/realglobe/api/npm/npm-virtual" > .npmrc
- curl -u${NPM_USER}:${NPM_PASSWORD} "https://realglobe.artifactoryonline.com/realglobe/api/npm/auth" >> .npmrc
- cat .npmrc
- npm install istanbul mocha babel-cli -g
- npm install babel-preset-es2015
before_script:
- npm link .
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
